server:
  port: 8001
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /docker-test
    session:
      timeout: 30M
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*